import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from "@/app/componets/auth/Provider";
import {NotificationManager} from "@/app/componets/popup/notification/NotificationManager";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
            <Provider>
                <NotificationManager>
                    {children}
                </NotificationManager>
            </Provider>
        </body>
      </html>
  )
}
